// 24 Premium Andhra Sweets and Savories Mock Database
export const PRODUCTS_DATA = [
  {
    id: "p1",
    slug: "bellam-putharekulu",
    name: "Special Atreyapuram Bellam Putharekulu",
    description: "Paper-thin wafer layers folded with ghee, jaggery, and premium cashew bits, crafted in Atreyapuram.",
    price: 350,
    discountPrice: 299,
    rating: 4.9,
    reviewCount: 148,
    weight: "250g (10 Pcs)",
    category: "Traditional Sweets",
    stock: 25,
    featured: true,
    bestSeller: true,
    color: "from-amber-100 to-orange-200",
    textColor: "text-amber-800",
    sweetType: "traditional",
    ingredients: "Fine Rice Starch Wafer, Pure Desi Ghee, Organic Bellam (Jaggery), Grated Cashew Nuts, Almonds.",
    nutrition: { calories: "180 kcal", fat: "8g", sugar: "12g", protein: "2g" },
    shelfLife: "20 Days",
    storage: "Store in a cool dry place. Keep in an airtight dry container to maintain crispness."
  },
  {
    id: "p2",
    slug: "kaju-katli",
    name: "Premium Kaju Katli",
    description: "Mouth-melting diamond-shaped cashew fudge decorated with premium edible silver leaf.",
    price: 650,
    discountPrice: 599,
    rating: 4.8,
    reviewCount: 232,
    weight: "500g",
    category: "Dry Fruit Sweets",
    stock: 40,
    featured: true,
    bestSeller: true,
    color: "from-amber-50 to-yellow-150",
    textColor: "text-yellow-800",
    sweetType: "dryfruit",
    ingredients: "Premium Cashew Nuts (Kaju), Refined Sugar, Cardamom, Pure Silver Leaf (Vark).",
    nutrition: { calories: "220 kcal", fat: "11g", sugar: "15g", protein: "4g" },
    shelfLife: "15 Days",
    storage: "Store in a cool, dry place. Keep away from direct sunlight."
  },
  {
    id: "p3",
    slug: "ghee-ariselu",
    name: "Pure Ghee Ariselu",
    description: "Traditional deep-fried rice flour and jaggery cakes garnished with white sesame seeds.",
    price: 420,
    discountPrice: 380,
    rating: 4.7,
    reviewCount: 94,
    weight: "500g",
    category: "Traditional Sweets",
    stock: 15,
    featured: true,
    bestSeller: true,
    color: "from-orange-100 to-amber-200",
    textColor: "text-orange-950",
    sweetType: "traditional",
    ingredients: "Soaked Rice Flour, Pure Ghee, Organic Jaggery, Sesame Seeds.",
    nutrition: { calories: "210 kcal", fat: "9g", sugar: "18g", protein: "2g" },
    shelfLife: "12 Days",
    storage: "Keep in a cool dry place in an airtight jar. Best consumed fresh."
  },
  {
    id: "p4",
    slug: "kakinada-gaja-kaja",
    name: "Kakinada Gaja Kaja",
    description: "Juicy layered flour scrolls soaked in warm sugar syrup, crunchy on the outside, syrup-filled inside.",
    price: 380,
    discountPrice: 330,
    rating: 4.8,
    reviewCount: 110,
    weight: "500g",
    category: "Traditional Sweets",
    stock: 12,
    featured: true,
    bestSeller: false,
    color: "from-amber-100 to-yellow-200",
    textColor: "text-amber-900",
    sweetType: "traditional",
    ingredients: "Refined Wheat Flour (Maida), Pure Ghee, Cardamom, Sugar Syrup.",
    nutrition: { calories: "240 kcal", fat: "10g", sugar: "25g", protein: "3g" },
    shelfLife: "10 Days",
    storage: "Keep at room temperature. Keep container closed tightly."
  },
  {
    id: "p5",
    slug: "pure-ghee-palkova",
    name: "Pure Ghee Palkova",
    description: "Slow-simmered condensed milk fudge flavored with green cardamom and ghee.",
    price: 280,
    discountPrice: 240,
    rating: 4.9,
    reviewCount: 185,
    weight: "250g",
    category: "Milk Sweets",
    stock: 20,
    featured: true,
    bestSeller: true,
    color: "from-orange-50 to-orange-150",
    textColor: "text-orange-900",
    sweetType: "milk",
    ingredients: "Condensed Whole Milk, Sugar, Ghee, Cardamom Powder.",
    nutrition: { calories: "190 kcal", fat: "8g", sugar: "18g", protein: "4g" },
    shelfLife: "8 Days",
    storage: "Refrigeration recommended for longer freshness. Consume within 8 days."
  },
  {
    id: "p6",
    slug: "andhra-kara-boondi",
    name: "Andhra Kara Boondi",
    description: "Crispy chickpea flour tiny drops fried with peanuts, cashews, garlic, and curry leaves.",
    price: 180,
    discountPrice: 150,
    rating: 4.6,
    reviewCount: 76,
    weight: "250g",
    category: "Namkeen",
    stock: 35,
    featured: true,
    bestSeller: false,
    color: "from-yellow-100 to-amber-250",
    textColor: "text-yellow-950",
    sweetType: "savory",
    ingredients: "Bengal Gram Flour, Peanuts, Cashew Nuts, Garlic, Curry Leaves, Chilli Powder, Salt.",
    nutrition: { calories: "150 kcal", fat: "9g", sugar: "1g", protein: "3g" },
    shelfLife: "30 Days",
    storage: "Keep in a completely dry place inside an airtight box to keep crispy."
  },
  {
    id: "p7",
    slug: "assorted-dry-fruit-roll-box",
    name: "Assorted Dry Fruit Roll Box",
    description: "Luxury sugar-free rolls made of figs, dates, cashews, almonds, and pistachios.",
    price: 850,
    discountPrice: 749,
    rating: 4.9,
    reviewCount: 64,
    weight: "500g",
    category: "Dry Fruit Sweets",
    stock: 18,
    featured: true,
    bestSeller: true,
    color: "from-amber-200 to-orange-300",
    textColor: "text-orange-950",
    sweetType: "dryfruit",
    ingredients: "Dried Figs (Anjeer), Dates, Cashews, Almonds, Pistachios, Cardamom.",
    nutrition: { calories: "170 kcal", fat: "7g", sugar: "9g", protein: "4g" },
    shelfLife: "30 Days",
    storage: "Store in dry place. No refrigeration needed."
  },
  {
    id: "p8",
    slug: "signature-festival-sweet-box",
    name: "Signature Festival Sweet Box",
    description: "A gorgeous curated box containing Putharekulu, Kaju Katli, Ariselu, and Palkova.",
    price: 1200,
    discountPrice: 999,
    rating: 5.0,
    reviewCount: 312,
    weight: "1kg (Assorted)",
    category: "Gift Boxes",
    stock: 30,
    featured: true,
    bestSeller: true,
    color: "from-purple-100 to-pink-200",
    textColor: "text-purple-900",
    sweetType: "gift",
    ingredients: "Assortment of Milk, Dry Fruit, and Traditional Sweets. (Contains Nuts & Dairy).",
    nutrition: { calories: "210 kcal (Avg)", fat: "10g", sugar: "16g", protein: "3g" },
    shelfLife: "10 Days",
    storage: "Keep in a cool place. Distribute and consume within shelf life."
  },
  {
    id: "p9",
    slug: "special-ghee-laddu",
    name: "Special Ghee Motichoor Laddu",
    description: "Fine chickpea flour tiny beads fried in desi ghee, bound with syrup, and shaped into sweet round laddus.",
    price: 360,
    discountPrice: 320,
    rating: 4.8,
    reviewCount: 198,
    weight: "500g",
    category: "Milk Sweets",
    stock: 22,
    featured: false,
    bestSeller: true,
    color: "from-orange-100 to-yellow-250",
    textColor: "text-orange-900",
    sweetType: "milk",
    ingredients: "Gram Flour, Pure Ghee, Sugar, Cashew Nuts, Cardamom, Melon Seeds.",
    nutrition: { calories: "230 kcal", fat: "11g", sugar: "20g", protein: "3g" },
    shelfLife: "8 Days",
    storage: "Keep in a dry airtight box. Do not refrigerate to prevent hardening."
  },
  {
    id: "p10",
    slug: "dry-fruit-halwa",
    name: "Rich Dry Fruit Halwa",
    description: "Gelled wheat-starch halwa packed with crunchy cashew nuts, almonds, and pistachios.",
    price: 490,
    discountPrice: 425,
    rating: 4.6,
    reviewCount: 54,
    weight: "500g",
    category: "Dry Fruit Sweets",
    stock: 14,
    featured: false,
    bestSeller: false,
    color: "from-amber-100 to-rose-200",
    textColor: "text-amber-950",
    sweetType: "dryfruit",
    ingredients: "Wheat Starch, Ghee, Sugar, Cashews, Almonds, Pistachios, Cardamom.",
    nutrition: { calories: "260 kcal", fat: "13g", sugar: "22g", protein: "3g" },
    shelfLife: "25 Days",
    storage: "Store at room temperature in a sealed dry container."
  },
  {
    id: "p11",
    slug: "milk-mysore-pak",
    name: "Pure Ghee Mysore Pak",
    description: "A rich melt-in-the-mouth sweet made of chickpea flour, sugar, and generous desi ghee.",
    price: 480,
    discountPrice: 440,
    rating: 4.9,
    reviewCount: 172,
    weight: "500g",
    category: "Traditional Sweets",
    stock: 25,
    featured: false,
    bestSeller: true,
    color: "from-yellow-100 to-amber-200",
    textColor: "text-amber-900",
    sweetType: "traditional",
    ingredients: "Bengal Gram Flour, Desi Ghee, Refined Sugar.",
    nutrition: { calories: "280 kcal", fat: "16g", sugar: "22g", protein: "2g" },
    shelfLife: "20 Days",
    storage: "Keep in dry container. Keep lid closed to prevent dampness."
  },
  {
    id: "p12",
    slug: "rasmalai-cup",
    name: "Classic Kesar Rasmalai",
    description: "Soft spongy cheese patties squeezed and soaked in sweet saffron milk, topped with pistachios.",
    price: 320,
    discountPrice: 280,
    rating: 4.9,
    reviewCount: 220,
    weight: "500g (5 Pcs)",
    category: "Bengali Sweets",
    stock: 10,
    featured: false,
    bestSeller: true,
    color: "from-rose-50 to-rose-100",
    textColor: "text-rose-900",
    sweetType: "bengali",
    ingredients: "Cottage Cheese (Chhena), Milk Cream, Sugar, Saffron, Pistachio Flakes, Cardamom.",
    nutrition: { calories: "160 kcal", fat: "6g", sugar: "14g", protein: "5g" },
    shelfLife: "3 Days",
    storage: "Refrigerate immediately. Serve chilled."
  },
  {
    id: "p13",
    slug: "cham-cham-sweet",
    name: "Kesar Cham Cham",
    description: "Traditional Bengali cylindrical chhena sweets cooked in light sugar syrup, coated with coconut.",
    price: 340,
    discountPrice: 299,
    rating: 4.5,
    reviewCount: 42,
    weight: "500g",
    category: "Bengali Sweets",
    stock: 15,
    featured: false,
    bestSeller: false,
    color: "from-rose-100 to-pink-200",
    textColor: "text-rose-905",
    sweetType: "bengali",
    ingredients: "Cottage Cheese (Chhena), Sugar Syrup, Desiccated Coconut, Saffron.",
    nutrition: { calories: "180 kcal", fat: "5g", sugar: "19g", protein: "4g" },
    shelfLife: "4 Days",
    storage: "Keep refrigerated. Best consumed within 4 days."
  },
  {
    id: "p14",
    slug: "andhra-chekkalu",
    name: "Traditional Chekkalu",
    description: "Crispy flat rice crackers seasoned with green chillies, ginger, and curry leaves.",
    price: 190,
    discountPrice: 160,
    rating: 4.7,
    reviewCount: 88,
    weight: "250g",
    category: "Namkeen",
    stock: 30,
    featured: false,
    bestSeller: true,
    color: "from-yellow-100 to-amber-200",
    textColor: "text-amber-950",
    sweetType: "savory",
    ingredients: "Rice Flour, Chana Dal, Ginger-Green Chilli Paste, Butter, Curry Leaves, Salt.",
    nutrition: { calories: "140 kcal", fat: "7g", sugar: "0g", protein: "2g" },
    shelfLife: "25 Days",
    storage: "Store in dry place in an airtight tin to avoid sogginess."
  },
  {
    id: "p15",
    slug: "ribbon-murukku",
    name: "Crispy Ribbon Pakoda",
    description: "Savory ribbon-like strips made of rice and chickpea flour with a hint of asafoetida.",
    price: 180,
    discountPrice: 145,
    rating: 4.6,
    reviewCount: 47,
    weight: "250g",
    category: "Namkeen",
    stock: 45,
    featured: false,
    bestSeller: false,
    color: "from-yellow-100 to-amber-150",
    textColor: "text-yellow-900",
    sweetType: "savory",
    ingredients: "Rice Flour, Besan, Ghee, Chilli Powder, Carom Seeds (Ajwain), Asafoetida, Salt.",
    nutrition: { calories: "145 kcal", fat: "8g", sugar: "0g", protein: "2.5g" },
    shelfLife: "30 Days",
    storage: "Keep container tightly closed in dry pantry."
  },
  {
    id: "p16",
    slug: "spicy-janthikalu",
    name: "Spicy Andhra Janthikalu",
    description: "Crunchy spiral snacks prepared using rice flour and black gram flour with sesame and chilli.",
    price: 195,
    discountPrice: 165,
    rating: 4.8,
    reviewCount: 79,
    weight: "250g",
    category: "Namkeen",
    stock: 25,
    featured: false,
    bestSeller: true,
    color: "from-orange-100 to-yellow-200",
    textColor: "text-orange-950",
    sweetType: "savory",
    ingredients: "Rice Flour, Urad Dal Flour, Sesame Seeds, Red Chilli Powder, Butter, Salt.",
    nutrition: { calories: "155 kcal", fat: "9g", sugar: "0g", protein: "3g" },
    shelfLife: "30 Days",
    storage: "Airtight dry storage container is critical to maintain crispness."
  },
  {
    id: "p17",
    slug: "almond-house-assorted-box",
    name: "Curated Dry Fruit Assortment Box",
    description: "Elegant gifting container loaded with premium dry fruit bites and dates rolls.",
    price: 950,
    discountPrice: 850,
    rating: 4.9,
    reviewCount: 52,
    weight: "500g",
    category: "Gift Boxes",
    stock: 12,
    featured: false,
    bestSeller: false,
    color: "from-purple-100 to-pink-200",
    textColor: "text-purple-900",
    sweetType: "gift",
    ingredients: "Figs, Apricots, Dates, Almonds, Cashews, Pistachios, Cardamom.",
    nutrition: { calories: "185 kcal", fat: "8g", sugar: "10g", protein: "4g" },
    shelfLife: "25 Days",
    storage: "Store in a dry location. Keep away from heat."
  },
  {
    id: "p18",
    slug: "special-badam-halwa",
    name: "Signature Badam Halwa",
    description: "Premium almond paste slow-cooked in pure ghee and sugar, flavored with saffron.",
    price: 750,
    discountPrice: 680,
    rating: 4.9,
    reviewCount: 164,
    weight: "250g",
    category: "Dry Fruit Sweets",
    stock: 15,
    featured: false,
    bestSeller: true,
    color: "from-amber-100 to-yellow-250",
    textColor: "text-amber-900",
    sweetType: "dryfruit",
    ingredients: "Blanched Almonds (Badam), Pure Ghee, Sugar, Saffron, Cardamom.",
    nutrition: { calories: "290 kcal", fat: "18g", sugar: "25g", protein: "5g" },
    shelfLife: "15 Days",
    storage: "Keep refrigerated for better freshness. Heat slightly before serving."
  },
  {
    id: "p19",
    slug: "premium-anjeer-roll",
    name: "Premium Sugar-Free Anjeer Roll",
    description: "A healthy sugar-free sweet made using organic figs and loaded with chopped nuts.",
    price: 680,
    discountPrice: 620,
    rating: 4.8,
    reviewCount: 92,
    weight: "500g",
    category: "Dry Fruit Sweets",
    stock: 18,
    featured: false,
    bestSeller: false,
    color: "from-amber-200 to-orange-200",
    textColor: "text-amber-950",
    sweetType: "dryfruit",
    ingredients: "Dry Figs (Anjeer), Cashews, Almonds, Pistachios, Dates.",
    nutrition: { calories: "165 kcal", fat: "7g", sugar: "8g", protein: "3.8g" },
    shelfLife: "30 Days",
    storage: "Keep in a cool dry drawer. Close container lid."
  },
  {
    id: "p20",
    slug: "mango-kalakand",
    name: "Summer Special Mango Kalakand",
    description: "Soft grainy milk cake cooked with rich mango pulp and sugar, garnished with pistachios.",
    price: 360,
    discountPrice: 310,
    rating: 4.7,
    reviewCount: 120,
    weight: "500g",
    category: "Milk Sweets",
    stock: 0, // OUT OF STOCK
    featured: false,
    bestSeller: false,
    color: "from-orange-100 to-yellow-200",
    textColor: "text-orange-900",
    sweetType: "milk",
    ingredients: "Condensed Milk, Curdled Milk Solids, Alphanso Mango Pulp, Sugar, Pistachio.",
    nutrition: { calories: "195 kcal", fat: "8g", sugar: "19g", protein: "4g" },
    shelfLife: "5 Days",
    storage: "Refrigerate immediately. Consume chilled."
  },
  {
    id: "p21",
    slug: "rasgulla-tin",
    name: "Soft Spongy Rasgulla Tin",
    description: "Traditional spongy round chhena balls cooked and preserved in light cardamom sugar syrup.",
    price: 260,
    discountPrice: 220,
    rating: 4.7,
    reviewCount: 154,
    weight: "1kg (12 Pcs)",
    category: "Bengali Sweets",
    stock: 30,
    featured: false,
    bestSeller: true,
    color: "from-rose-50 to-rose-100",
    textColor: "text-rose-900",
    sweetType: "bengali",
    ingredients: "Chhena (Milk Curds), Sugar Syrup, Cardamom flavoring.",
    nutrition: { calories: "125 kcal", fat: "2g", sugar: "22g", protein: "3.5g" },
    shelfLife: "180 Days (Sealed)",
    storage: "Store in a cool place. Refrigerate once opened and consume within 5 days."
  },
  {
    id: "p22",
    slug: "dry-fruit-kaju-katli",
    name: "Dry Fruit Filled Kaju Katli",
    description: "Double layered cashew diamond fudge filled with a core of figs, pistachios, and almonds.",
    price: 720,
    discountPrice: 650,
    rating: 4.9,
    reviewCount: 84,
    weight: "500g",
    category: "Dry Fruit Sweets",
    stock: 8,
    featured: false,
    bestSeller: false,
    color: "from-amber-50 to-yellow-200",
    textColor: "text-yellow-900",
    sweetType: "dryfruit",
    ingredients: "Cashews, Sugar, Ghee, Almonds, Pistachios, Dried Figs, Silver Leaf.",
    nutrition: { calories: "235 kcal", fat: "12g", sugar: "14g", protein: "4.2g" },
    shelfLife: "15 Days",
    storage: "Store in a sealed box in a dry, cool cabinet."
  },
  {
    id: "p23",
    slug: "special-bobbatlu",
    name: "Classic Ghee Bobbatlu / Polelu",
    description: "Soft, thin flatbreads stuffed with sweet chana dal and jaggery mixture, roasted with pure ghee.",
    price: 300,
    discountPrice: 260,
    rating: 4.8,
    reviewCount: 142,
    weight: "5 Pcs",
    category: "Traditional Sweets",
    stock: 0, // OUT OF STOCK
    featured: false,
    bestSeller: false,
    color: "from-yellow-100 to-amber-250",
    textColor: "text-amber-950",
    sweetType: "traditional",
    ingredients: "Refined Wheat Flour, Bengal Gram Dal, Organic Jaggery, Desi Ghee, Cardamom.",
    nutrition: { calories: "190 kcal", fat: "6g", sugar: "16g", protein: "3.5g" },
    shelfLife: "4 Days",
    storage: "Refrigerate if not consumed within 24 hours. Heat slightly on pan with ghee before eating."
  },
  {
    id: "p24",
    slug: "andhra-murukulu",
    name: "Ghee Roasted Murukulu",
    description: "Traditional savory snack made of rice flour and spices, shaped into concentric rings.",
    price: 180,
    discountPrice: 150,
    rating: 4.6,
    reviewCount: 65,
    weight: "250g",
    category: "Namkeen",
    stock: 20,
    featured: false,
    bestSeller: false,
    color: "from-yellow-100 to-amber-200",
    textColor: "text-yellow-950",
    sweetType: "savory",
    ingredients: "Rice Flour, Butter, Desi Ghee, Cumin Seeds, Carom Seeds, Red Chilli Powder, Salt.",
    nutrition: { calories: "148 kcal", fat: "8g", sugar: "0g", protein: "2g" },
    shelfLife: "30 Days",
    storage: "Keep in an airtight jar in a completely dry place."
  }
];
